### PR TITLE
fix #37 - number grouping in event parser

### LINKED ISSUE #37: event parser handles numbers with grouping incorrectly

### PR DESCRIPTION
**Pull request by jrpie**

### CODE REVIEW

File: app/src/main/java/eu/jonahbauer/qed/model/parser/EventParser.java [hunk 1]
```diff
@@ -174,6 +174,7 @@ static Double parseCost(@NonNull Element element) {
             String match = matcher.group(1);
             assert match != null;
 
+            match = match.replaceAll("\\.","");
```
Comment (jbb01) [inline app/src/main/java/eu/jonahbauer/qed/model/parser/EventParser.java:177]: Using `String#replace(CharSequence, CharSequence)` would avoid the additional overhead of RegExp parsing.

**Review by jbb01 — CHANGES_REQUESTED** [review]

**Review by jbb01 — APPROVED** [review]
